### ISSUE TITLE
[Feature Request]  Store + SqlDelight + Paging3 Guidance

### ISSUE THREAD

**Issue by JvmName** [MobileNativeFoundation/Store#250]
Specifically, I'm looking for guidance on how to tie Store, Paging3, and SqlDelight together. 

In a perfect world, Store wouldn't need to be part of the equation -- I should just be able to use Paging3+SqlDelight. However, that puts me in a weird situation: when I _need_ paging, I use use _Some Repository Pattern Type 1_, and when I _don't_ need paging, I use Store/_Some Other Repository Pattern_. In essence, it seems to me that Paging is an implementation detail, and that Store (or whatever my Repo layer is) should abstract over that. 

**Suggestion 1 - Paging-specific artifact**
Store adds a new `*-paging3` artifact that pegs a new `withPaging(androidx.paging.PagingSource)` builder method onto the `StoreBuilder`. The builder then provides a standard Store object that also happens to implement the `RemoteMediator` interface. (As an aside, if you squint, `RemoteMediator` looks pretty similar to the Store signature). 
Using this Store|RemoteMediator, I can then wire the downstream paging dependencies as necessary -- the Repository (i.e. Store) papers over the DB+Network (as Store already does) and handles the request of new info as the viewport changes (as Paging does). 

**Suggestion 2 - Code Sample**
Something like the above could be a PITA to maintain, especially since Paging3 is still in alpha...I'd also be happy with guidance on how to tie a non-Room DB to Paging using Store as an intermediary. That could be in the form of a sample, or a wiki...dealer's choice!

BTW Store is a super cool library, thanks for all the time and effort y'all spent on it 😄

**Comment by digitalbuddha** [comment]
Hello just checking in, I don't have a good answer/solution as of yet.

**Comment by Ghanem21** [comment]
Hi , I'm new in Gsoc is there is microtasks could I start with it to be familiar with the project 😊

**Comment by Saurabh-Mokashi** [comment]
Hi @digitalbuddha , Im interested to work on this issue as a part of GSoC2022. Kindly guide me through the next steps

**Comment by CEO-CGS** [comment]
Hello @digitalbuddha and @chris-mitchell, I am interested to work on this project as part of GSoC2022 as well and it would be a nice complement to the experience I have already with Android application development in Android Studio and Unity.

**Comment by JvmName** [comment]
Y'all this isn't a jobs board, either identify an area to contribute to or don't, but please stop just asking for people to enumerate how to contribute to an open source project

**Comment by CEO-CGS** [comment]
> Hi folks hold tight, there will be some messaging from dropbox coming along with how to join the google summer of code projects

Ok thanks.

**Comment by Sohailshah20** [comment]
Hello @digitalbuddha, I'm very interested in working on this project as a part of GSoC 2022. Further guidance for the onboarding process would be much appriciated.

**Comment by changusmc** [comment]
> Hi @digitalbuddha , Im interested to work on this issue as a part of GSoC2022. Kindly guide me through the next steps

> > Hi folks hold tight, there will be some messaging from dropbox coming along with how to join the google summer of code projects
> 
> Ok thanks.

> Hello @digitalbuddha, I'm very interested in working on this project as a part of GSoC 2022. Further guidance for the onboarding process would be much appriciated.

Due to some personnel transitions, we unfortunately had to pull Store from GSOC2022. We sincerely apologize for the inconvenience

**Comment by Kshitij09** [comment]
`paging3` integration with `Store` is something I'm interested to explore. Should I go ahead with the same or is there any other high-priority issue currently being worked upon that I could contribute to?

`Store` is an excellent Library and am looking forward to contributing 🙂
