### ISSUE TITLE
[Feature Request] Please add better documentation

### ISSUE THREAD

**Issue by itsandreramon** [MobileNativeFoundation/Store#277]
Please provide a better documentation on how to use it with different use cases. For instance reading all items or reading a single item using Store. While I know how to setup this up, best practices are not clear from the current readme.

Also, the example omits precious type information and locally used datasource to be able to use method references like shown here:

```
StoreBuilder
    .from(
        fetcher = Fetcher.of { api.fetchSubreddit(it, "10").data.children.map(::toPosts) },
        sourceOfTruth = SourceOfTruth.of(
            reader = db.postDao()::loadPosts,
            writer = db.postDao()::insertPosts,
            delete = db.postDao()::clearFeed,
            deleteAll = db.postDao()::clearAllFeeds
        )
    ).build()
```

Maybe consider adding a sample?

Also, how to handle Nullability inside the fetcher? What if my API does return null? The Store only accepts Any as output or is this something that is handled internally and then it just returns the onError response?

**Comment by digitalbuddha** [comment]
https://github.com/dropbox/Store/tree/main/app should have a sample or two but is primed for a refactor. Let me think about some improvements.

As for nullability inside a fetcher you have two options: if null is a valid value I would recommend transforming it to some other marker (null object pattern). If null is an unexpected value I'd recommend throwing an exception instead. I'm afk today but will link the past issues/discussions about null handling.

Hope that helps
