### ISSUE TITLE
[Feature Request] Declarative tooling for Compose

### ISSUE THREAD

**Issue by salan1** [MobileNativeFoundation/Store#287]
**Is your feature request related to a problem? Please describe.**
With Compose v1 out it would be nice to have some declarative tooling added to the library.

**Describe the solution you'd like**
A set of effects to enable the collection of data from within composables.
For example, an effect that can return a mutable state generated from the flow of items emitted from the store and maybe other utility funcs.

From this
```
val article = store.get(key)
updateUI(article)
```
to

`val (data, error, refetch, clear) = useStore(key)`

**Additional context**
  Really looking for a set of tools similar to what React-Query provides but for Compose. [https://react-query.tanstack.com/guides/queries](url)

**Comment by digitalbuddha** [comment]
Looks neat. I'm going to read more about it. Let me know if you or anyone else have thoughts on perspective api. Sounds like our base apis are in good shape but we can use some better high level public apis.

**Comment by salan1** [comment]
My example was a bit incorrect since it doesn't have a reference to a store. You could possibly have useStore(key, storeRef) but this would require passing the store down to the composable which would reduce the impact that the query would have in increasing the reusability of compsables without the need of a ViewModel. 

Instead, stores could be passed down through a CompositionLocal provider and have a query as such
`useStore(storeKey, fetchKey)`. Possibly, the query could also allow the creation of Stores, this would require the library to have some means of storing the Stores on its own. But it would allow Stores to be used completely within composables. Users would still need to provide their own HTTP client or any other source. 

`StoreProvider(storeContainer, etc...){App()}`

```
useStore(storeKey, fetchKey, options){
    Fetcher.ofFlow { articleId -> api.getArticle(articleId) })
}
```

It would need to expose everything that a composable would need typically need to drive the UI.
**Just to list a few things:**
- **data**: The cached or fresh data 
- **isLoading**: Whether the fetcher is currently fetching the data.
- **error**: Errors produced from the fetcher or store
- **reFetch()**: Reexecute the Fetcher for the current keys
- **manual**: Some way of preventing the fetcher from being called until reFetch is called. Important if the keys are not yet ready e.g. some form data.
- **keepPreviousData**: Does not clear the current cache or load the next fetch if keys have changed until a refetch is successful. Really useful for paginated requests to avoid recomposistions when changing between pages.

**Comment by OrhanTozan** [comment]
I recommend using a different return type. I get that the (data, loading, error) pattern is popular in JS land, but the truth is we have sealed classes in Kotlin. Let the type say "its either error, loading or data", instead of "it can have error, and also data", while that ofcourse will never happen.

**Comment by digitalbuddha** [comment]
It's not clear to my how useStore is any better than a store builder inside of a CompositionLocal, mind explaining what the additional api surface gets us? We are still experimenting with compose and finding the right patters to use

**Comment by sdoward** [comment]
Adding my 2 cents... I feel like store and compose operate on different layers and solve different problems. I feel like adding `MutableState` to the api makes it less clean.. The concerns of store become mixed.

It is not too difficult for the consumers of store to map to compose-related data structures. Compose itself offers utility functions mapping `Flow` -> `MutableState`

**Comment by salan1** [comment]
I was hoping to respond to this once I had more time on Compose but going to close this since flows can be simply mapped to a `MutableState` state for a base use and other utilities I'll just make independently since the majority of what I mentioned above is a pattern I'd like to carry on from my RN projects.
