### ISSUE TITLE
[BUG] Pull to refresh causes exponential calls

### ISSUE THREAD

**Issue by MKelman** [MobileNativeFoundation/Store#310]
**Describe the bug**
With the implementation of store using coroutine flow and the store implementation returning store.stream(request) where the request contains a StoreRequest.fresh, we are seeing that on every pull refresh, the collect storeResponse is being called numerous times with exponential calls.

```
viewModelScope.launch(dispatcher) {
       updateTransactions.run(params).collect {
           LogHelper.d("test: refreshTransactions 3")
           state.postValue(it)
       }
}
```

In the following code above, we start a coroutine flow call with a postValue to let us know what is returned. This log helper helped us understand that every time a user pulls to refresh, this gets called with exponential growth. First pull to refresh may be 2-3 calls, then on 2nd pull to refresh 6 calls, then 10 calls. Inside of the coroutine Etc. This would also call the reader inside of the source of truth with that many times as well.

For one of our pages, we had to move away from flow to make a store.get(“key”) to fix this issue so that it would not “flicker” the ui many times which ended up crashing the app after 3-4 pull to refreshes. 

**To Reproduce**
1. pull to refresh a page that is being viewed 

**Expected behavior**
doesn't cause exponential calls and only calls the source of truth once without having to use store.get("key") and to continue using the flow

**Comment by digitalbuddha** [comment]
Could you make a full reproducible sample/test that I can play with? It's unclear to me why it would go 3,6,10 refreshes, I have not seen similar and must be using differently than y'all 😁

**Comment by digitalbuddha** [comment]
Tough to say without knowing exactly what you are doing. 

Pull latest from main branch and take a look out or sample app. Particularly the following fragment. I have not heard of reports of similar. If you can reproduce there we can fix. https://github.com/dropbox/Store/blob/main/app/src/main/java/com/dropbox/android/sample/ui/room/RoomFragment.kt

**Comment by MKelman** [comment]
@digitalbuddha sample app now works. While i have not reproduced my exact issue on the sample app, I am curious as to why a pull to refresh causes the collect to be hit 3 times here. Those are all the calls made in just one pull to refresh. The state: refresh  is coming from storeState.loading.collect { response 

![image](https://user-images.githubusercontent.com/10063610/137554147-3660d576-843e-4bef-9e00-b4b3ec75ec30.png)

**Comment by MKelman** [comment]
@digitalbuddha any updates on this?

**Comment by FilippoVigani** [comment]
@MKelman I think what you are seeing is the 3 data levels being received on the listener: the in-memory cache, the database cache and the remote data.

**Comment by matt-ramotar** [comment]
@MKelman Can you share the repo? Happy to take a look

**Comment by MKelman** [comment]
we have limited our use of store and not seeing this issue anymore from probably some hacky fixes. going to close this for now
