### ISSUE TITLE
[Store 5] Add bindings to KMP cache

### ISSUE THREAD

**Issue by matt-ramotar** [MobileNativeFoundation/Store#447]
- [ ] Create `CachingPersister` that delegates to [Cache](https://github.com/MobileNativeFoundation/Store/tree/Kmp/cache)

**Comment by digitalbuddha** [comment]
You can instead make a CachingPersister than delegates to Cache

**Comment by matt-ramotar** [comment]
Ah yeah Good idea 👍🏽

**Comment by matt-ramotar** [comment]
Closed with #493
