### ISSUE TITLE
[Store 5] Make Bookkeeper optional

### ISSUE THREAD

**Issue by matt-ramotar** [MobileNativeFoundation/Store#452]
As I wrote internally - I am not sure we need to require users pass in `Bookkeeper`. All `Bookkeper` needs to do is let `RealMarket` know it should eagerly resolve conflicts. Initially I thought we would want to defer implementation to users. But with `Bookkeeping` mental model, I suspect most users will not care to customize. We can bind `Bookkeeper` to a disk cache or DB ourselves under the hood and make it default implementation. Thoughts on making `Bookkeeper` optional?

_Originally posted by @matt-ramotar in https://github.com/MobileNativeFoundation/Store/pull/450#discussion_r968506868_

**Comment by aclassen** [comment]
Just wanna note, that if we wanna go for disk cache we would also need a kmp filesystem implementation. So i guess a DB would be a better fit to support all platforms.

**Comment by matt-ramotar** [comment]
Closing as #496 separated `Store` and `MutableStore`
