### ISSUE TITLE
[Feature Request] iOS simulator support in Store5

### ISSUE THREAD

**Issue by Joeywp** [MobileNativeFoundation/Store#511]
**Is your feature request related to a problem? Please describe.**
I have a project that uses a Kotlin Native iOS SImulator target (iosSimulatorArm64). As Store5 doesn't target this, it can't be used with projects that target the iOS simulator.

**Describe the solution you'd like**
I think that adding the `iosSimulatorArm64()` target to Store (next to `iosArm64()` and `iosX64()`) would solve this, but as I'm pretty new to multiplatform maybe there's a reason behind not having this enabled (yet)?

**Describe alternatives you've considered**
I cloned the repository locally and added to the 3 main gradle modules (cache, multicast & store) the iOS simulator target, which seemed to at least compile fine, but I wasn't sure about the implications this has as I'm pretty new to Kotlin multiplatform.

**Comment by matt-ramotar** [comment]
If I recall we hit an issue with some of our tests and decided to backlog

**Comment by Joeywp** [comment]
Unfortunately I can't easily sign CLA's at my job required for PRs, but as I had this issue with several other libraries as well I just disabled the simulator target for now at the project I'm working on.

As a side note, when I added those targets to my local clone, all tests ran using the check command succeeded, so perhaps the issue happening previously has been resolved recently?

**Comment by ema987** [comment]
I just made a PR adding the `iosSimulatorArm64` target.

In my experience, as also @Joeywp said, local checks are running successfully and the artifacts I built work in my project, running on the iOS simulator as well.
