### ISSUE TITLE
[Proposal] StatefulStore

### ISSUE THREAD

**Issue by matt-ramotar** [MobileNativeFoundation/Store#526]
## Abstract

Some reads require transformation by secondary API requests before presentation with validation criteria dependent on state. Store should support suspending transformation of reads and management of stateful output.

##### a) Some are driven entirely by server, some are hybrid
For example, there are modules entirely driven by a server-driven UI API. There are hybrid modules: Some UI is hardcoded, some comes from the server-driven UI API, some is backed by other internal APIs.

##### b) Each has different APIs and repositories
For example, there is a module backed by a server-driven UI API and several other internal APIs. The content from the server-driven UI API is a template. Each string can contain N variables that are determined at runtime. Some of these values live only on the client. So, we need to process each string after we receive it. For each variable in each string, we need to load the correct value, either from memory, disk, or network.

#### 2. **M Types**

<img src="https://user-images.githubusercontent.com/59468153/221614823-cded6f8f-1baa-4f8d-b7cb-b523ab41b7e9.png" height="200px" />

##### b) It must work offline
This is basic functionality users expect to work always without delay even when offline.

### Secondary API Requests + Validation Criteria Dependent On State

Templated strings are examples of a read response that requires transformation by secondary API requests before presentation with validation criteria dependent on state. One API provides the template. Other APIs provide the values that must be inserted before the text can be displayed. 

For example, the primary API response might include:

```kotlin
data class CarouselItem(
  val id: String,
  val name: String,
  val title: String,
  val subtitle: String,
  val label: String,
  val status: String,
  val action: Action,
)
```

Where:

```kotlin
title = "Manage offline files"
subtitle = "\${OFFLINE_FILE_COUNT} files"
label = "\${EFFECTIVE_PLAN}"
status = "\${OFFLINE_FILES_STATUS}"
```

Before we can present the carousel item, we need to make secondary API requests to determine:
1. Offline file count
2. Effective plan
3. Offline files status

The template (primary API response) might have a TTL of 24 hours. The inserted values (secondary API responses) might have TTLs of 2 minutes, 1 minute, and 10 minutes. 

## Proposal

Store should support suspending transformation of reads and management of stateful output. We should introduce `StatefulStore` and `Processor`. We should modify `RealStore` and `FetcherController`.

## Rationale

Currently, Store does not solve this problem. To solve this problem today with persistence of the transformed result, users need multiple persistence solutions and a custom manager that wires them together:

```kotlin
suspend fun Processor(userId: String, unprocessed: CarouselItem, statusStore: Store, countStore: Store): CarouselItem {

    var minTTL = Long.MAX_VALUE

    val title = unprocessed.title.asPerishable(userId, statusStore, countStore)
    minTTL = minOf(title.minBy { it.ttl }, minTTL)

    val subtitle = unprocessed.subtitle.asPerishable(userId, statusStore, countStore)
    minTTL = minOf(subtitle.minBy { it.ttl }, minTTL)

    val label = unprocessed.label.asPerishable(userId, statusStore, countStore)
    minTTL = minOf(label.minBy { it.ttl }, minTTL)

    val status = unprocessed.status.asPerishable(userId, statusStore, countStore)
    minTTL = minOf(status.minBy { it.ttl }, minTTL)

    return CarouselItem(
            id = unprocessed.id,
            name = unprocessed.name,
            title = title.map { it.value },
            subtitle = subtitle.map { it.value },
            label = label.map { it.value },
            status = status.map { it.value },
            action = unprocessed.action,
            ttl = minTTL
    )
```

```kotlin
suspend fun String.asPerishable(userId: String, statusStore: Store, countStore: Store): Perishable {
    var ttl: Long = Long.MAX_VALUE
    val value = split(SPACE).map { word ->
        val request = StoreReadRequest.cached(userId, false)
        when (val variable = Variable.lookup(word)) {
            Variable.Status -> {
                val status = statusStore.stream(request).first { it.dataOrNull() != null }.requireData()
                ttl = minOf(status.ttl, ttl)
                status.value
            }

            Variable.Count -> {
                val count = countStore.stream(request).first { it.dataOrNull() != null }.requireData()
                ttl = minOf(countStore.ttl, ttl)
                countStore.value
            }

            null -> word
        }
    }

    return Perishable(
            value = value.joinToString(SPACE),
            ttl = ttl,
    )
}
```

```kotlin
val unprocessedStore = StoreBuilder.from<String, CarouselItem, CarouselItem, CarouselItem>(
      fetcher = Fetcher.of { key -> api.get(key) },
      sourceOfTruth = SourceOfTruth.of(
              nonFlowReader = { key -> unprocessedDb.get(key) },
              writer = { key, item -> unprocessedDb.put(key, item) }
      ))
      .build()
)
```

```kotlin
val countStore = StoreBuilder.from<String, Int, Int, Int>(
      fetcher = Fetcher.of { key -> countApi.get(key) },
      sourceOfTruth = SourceOfTruth.of(
              nonFlowReader = { key -> countDb.get(key) },
              writer = { key, item -> countDb.put(key, item) }
      ))
      .validator(countValidator)
      .build()
)
```

```kotlin
val statusStore = StoreBuilder.from<String, String, String, String>(
      fetcher = Fetcher.of { key -> statusApi.get(key) },
      sourceOfTruth = SourceOfTruth.of(
              nonFlowReader = { key -> statusDb.get(key) },
              writer = { key, item -> statusDb.put(key, item) }
      ))
      .validator(statusValidator)
      .build()
)
```

```kotlin
val processedStore = StoreBuilder.from<String, CarouselItem, CarouselItem, CarouselItem>(
      fetcher = Fetcher.of { key ->
          val request = StoreReadRequest.cached(key, false)
          val unprocessed = unprocessedStore.stream(request).first { it.dataOrNull() != null }.requireData()
          Processor(
                  userId = key,
                  unprocessed = unprocessed,
                  statusStore = statusStore,
                  countStore = countStore
          )
      },
      sourceOfTruth = SourceOfTruth.of(
              nonFlowReader = { key -> processedDb.get(key) },
              writer = { key, item ->
                  processedDb.put(key, item)
              }
      )
)
.validator(carouselItemValidator)
.build()
```

This increases risk and maintenance and worsens readability and overall developer experience. Store should introduce the first iteration of an industry standard solution to these problems.

### RealStore + FetcherController
<img src="https://user-images.githubusercontent.com/59468153/221432292-86d7a2a5-1abb-48dc-99f0-cf89564a1e15.png" height="200px" />

### StatefulStoreKey
```kotlin
interface StatefulStoreKey {

    fun unprocessed(): Unprocessed
    fun processed(): Processed
    interface Processed : StatefulStoreKey {
        override fun processed() = this
    }

    interface Unprocessed : StatefulStoreKey {
        override fun unprocessed() = this
    }
}
```

### Processor
```kotlin
typealias Processor<Output> = suspend (output: Output) -> Output
```

### StatefulStore
```kotlin
interface StatefulStore<Key : StatefulStoreKey, Output : Any> :
        Read.Stream<Key, Output>,
        Clear.Key<Key>,
        Clear
```

## Sample

```kotlin
val countStore = StoreBuilder.from<String, Int, Int, Int>(
        fetcher = Fetcher.of { key -> api.get(key) },
        sourceOfTruth = SourceOfTruth.of(
                nonFlowReader = { key -> countDb.get(key) },
                writer = { key, item -> countDb.put(key, item) }
        ))
        .validator(validator)
        .build()
)
```

```kotlin
val statusStore = StoreBuilder.from<String, String, String, String>(
        fetcher = Fetcher.of { key -> api.get(key) },
        sourceOfTruth = SourceOfTruth.of(
                nonFlowReader = { key -> statusDb.get(key) },
                writer = { key, item -> statusDb.put(key, item) }
        ))
        .validator(validator)
        .build()
)
```

```kotlin
val statefulStore = StatefulStoreBuilder.from<String, CarouselItem, CarouselItem, CarouselItem>(
        fetcher = Fetcher.of { key -> api.get(key) },
        sourceOfTruth = SourceOfTruth.of(
                nonFlowReader = { key -> statefulDb.get(key) },
                writer = { key, item -> statefulDb.put(key, item) }
        ))
        .validator(validator)
        .build(Processor)
)
```

**Comment by digitalbuddha** [comment]
The thinking is to have a scoped/statefuk store where the key is a builder param. Effectively this allows us to call store.get without passing a param

**Comment by matt-ramotar** [comment]
@digitalbuddha Ah can you add a ticket for ScopedStore work? StatefulStore is something separate I have been thinking about. Organizing it as a proposal is helping clarify my thinking and will make shared mental model easier. Will update this issue soon. Hoping to get early feedback from you and community

**Comment by digitalbuddha** [comment]
Yup yup will do!
