### ISSUE TITLE
[BUG]Not enough information to infer type variable Output

### ISSUE THREAD

**Issue by Android1500** [MobileNativeFoundation/Store#544]
whenever i try to create StoreBuilder its give me error in from().

**Comment by Android1500** [comment]
<img width="960" alt="Screenshot 2023-04-12 120947" src="https://user-images.githubusercontent.com/78565059/231560455-29af96a3-1a86-4712-802f-a0ffe2b9598e.png">

**Comment by matt-ramotar** [comment]
Hey there - StoreBuilder takes a few generics. See https://github.com/MobileNativeFoundation/Store/blob/main/store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/StoreBuilder.kt#L76

**Comment by Android1500** [comment]
Thanks I manage to work it but after first time its load data but i don't know what goes wrong but now app get cresh whenever i try to load data from store

userRepo class
<img width="960" alt="Screenshot 2023-04-12 120947" src="https://user-images.githubusercontent.com/78565059/231662992-cf2f9ab4-e36a-44f7-bc3b-325e784774e7.png">

userviewModel class
<img width="960" alt="Screenshot 2023-04-12 223401" src="https://user-images.githubusercontent.com/78565059/231663115-cc63e48e-2bd4-4632-9476-3c9f67b2ebc5.png">

userinfofragment class here i m try to get store data
<img width="960" alt="Screenshot 2023-04-12 223424" src="https://user-images.githubusercontent.com/78565059/231663206-ae62438a-c909-4644-8ae8-04f5aecdd749.png">

**Comment by Android1500** [comment]
I fixed it it not relate to store5 it happen coz of server response
