### ISSUE TITLE
Inconsistent SourceOfTruth argument types

### ISSUE THREAD

**Issue by elroid** [MobileNativeFoundation/Store#558]
I'm attempting to upgrade from version `5.0.0-alpha03` to `5.0.0-beta01` and I'm having trouble reconciling the [changes that have been made](https://github.com/MobileNativeFoundation/Store/commit/e050a15afc21c22ffea10a6a7d5f1b436ee34a6a#diff-889f660a39d931f9bc1412b0366280095494dfe4459f4a37c6f39cf6241fa45cR70) as part of `5.0.0-alpha04`. Specifically one of the builders in `StoreBuilder` ([StoreBuilder.Companion#from(Fetcher<Key,Input>, SourceOfTruth<Key,Input>)](https://github.com/MobileNativeFoundation/Store/blob/main/store/src/commonMain/kotlin/org/mobilenativefoundation/store/store5/StoreBuilder.kt#L73)) has been changed so that the source of truth takes a `Key` and an `Input` (`Network`) instead of `Key` and `Local` (`Output`) as before. I find this hard to reconcile with the SourceOfTruth class which remains unchanged and whose types remain `Key` and `Local`. 

It looks like the tests all use the same type for Input and Output so perhaps this discrepancy fell through the cracks? As I understand it the source of truth only deals with local representations, not fetcher results. If I'm mistaken and this is indeed intentional, please advise how this is meant to work.

Also, it appears to me that [this comment](https://github.com/MobileNativeFoundation/Store/issues/554#issuecomment-1556304298) on another issue may be related.

**Comment by digitalbuddha** [comment]
Hello! apologies for this breaking change, I'm at a conference this week but will take a look over weekend/next week. I think this was an unintended breaking change

**Comment by digitalbuddha** [comment]
Fixed in #560
