### ISSUE TITLE
[BUG] Fix breaking changes with source of truth

### ISSUE THREAD

**Issue by digitalbuddha** [MobileNativeFoundation/Store#559]
Store 4 had a source of truth that can write one type and read another. During some work adding mutable store, we broke that contract. I'll be adding the functionality back, it was an unintentional oversight

**Comment by digitalbuddha** [comment]
Starting looking at it. This work should be completed by end of week. The goals are to push ant converter and local data type logic down to multable store apis leaving non mutable stores as binary compatibile with old

**Comment by digitalbuddha** [comment]
This is what I was thinking...cc @matt-ramotar 

| Operation | Store |  MutableStore |
| ------------- | ------------- | ------------- |
| Write | network  | network OR output |
| Read  |output  | output |



Need a way to convert output back to network or have a common type for writing

With a common type called Local and a converter construct
`interface Converter<Network : Any, Output : Any, Local : Any>`


| Operation | Store |  MutableStore |
| ------------- | ------------- | ------------- |
| Write | network.toLocal	  | network.toLocal OR output.toLocal |
| Read  |output  | output |



Effectively store will have a dummy converter that has same type for network and local for example
` DummyConverter<Network, Output>(): Converter<Network, Network, Output> `


Mutable store has a converter that needs to know how to go from network to local or from output to local
Source of truth will know how to write a local or read an output

Store never needs to know how to convert local to output, if user has same local read and write they would set local and output type to be same 

Builders will hide all the generic mess :-) 

Thoughts @matt-ramotar ?

**Comment by matt-ramotar** [comment]
SGTM 👍🏽

**Comment by SteinerOk** [comment]
Hey @digitalbuddha, any ETA for this release?
I want to migrate from v4 to v5, but cannot via this bug(

**Comment by digitalbuddha** [comment]
There is a snapshot available now, we are targeting next week for a beta01 release. Thank you for patience, I'm old and commit to too many things 😅

**Comment by jsilva05** [comment]
Hi!
Any news on the new release?
Thanks!

**Comment by digitalbuddha** [comment]
https://github.com/MobileNativeFoundation/Store/releases/tag/5.0.0-beta02 Is out
