### ISSUE TITLE
[Question] Data with nested keys

### ISSUE THREAD

**Issue by gregkerzhner** [MobileNativeFoundation/Store#568]
Question - does Store & MutableStore have the ability to handle data which has nested keys?  The classic example would be:

A list of TODO objects (key "todos_list")
A single TODO object in that list (key "todo_{id}")

A common API structure in this setup might be to have a GET "/todos" endpoint which fetches the whole list, and then a PUT "/todo/id" endpoint which updates a single TODO.  

With this setup, consider the Store doing the following operations:
1. get "todos_list" from the server
2. Update some data on "todo_1" 
3. get "todos_list" from the server again.

In the above example, since the key for "todo_1" is different than "todos_list", would Store not detect a conflict between operations 2 and 3, meaning that operation 3 would potentially overwrite operation 2's data?   What is the recommended way to use Store to handle this kind of situation?

Thanks!

**Comment by matt-ramotar** [comment]
Hey @gregkerzhner Sorry to be slow. Very busy few weeks. Documentation is WIP but if I am understanding correctly I'd recommend using Store5 with [MultiCache](https://github.com/MobileNativeFoundation/Store/blob/main/cache/src/commonMain/kotlin/org/mobilenativefoundation/store/cache5/MultiCache.kt). Check out these:
- [Data model](https://github.com/MobileNativeFoundation/Store/blob/main/store/src/commonTest/kotlin/org/mobilenativefoundation/store/store5/util/model/NoteData.kt)
- [MultiCache usage](https://github.com/MobileNativeFoundation/Store/blob/main/store/src/commonTest/kotlin/org/mobilenativefoundation/store/store5/MutableStoreWithMultiCacheTests.kt)
- [More context on MultiCache](https://github.com/MobileNativeFoundation/Store/releases/tag/v5.0.0-beta01)
