### ISSUE TITLE
[BUG] Stop with the breaking API changes in beta

### ISSUE THREAD

**Issue by chrisbanes** [MobileNativeFoundation/Store#570]
5.0.0-beta02 changes the API again in a breaking way. I get that you want to change things, but can you do so in a non-breaking way? 

I recommend exporting the API to a file (using something like [binary-compatibility-validator ](https://github.com/Kotlin/binary-compatibility-validator) or [metalava-gradle](https://github.com/tylerbwong/metalava-gradle)) so you can keep track of API changes.

**Comment by digitalbuddha** [comment]
Sorry beta 02 should have returned the API to non breaking with Store4. Sounds like I need to do a better job comparing the two

**Comment by digitalbuddha** [comment]
Hey, I tried to compare store4 with the latest beta and I don't seem to see api differences in store/SOT/cache. Could you point me to where the issue is and I will fix in next beta, thank you!

**Comment by chrisbanes** [comment]
Yeah the issue was between 5.0.0-beta01 and 5.0.0-beta02, with changes in the `SourceOfTruth` class declaration. I'm happy if we're getting back to parity with Store4. I still think adding API validation is good practice for libraries, but I'll let you decide on that.

**Comment by digitalbuddha** [comment]
Absolutely. We had it and then lost during 5.0 migration. Will add back in to make usage easier. Thank you for feedback ♥️
