### ISSUE TITLE
[BUG] 5.0.0-beta02 breaks StoreReadRequest.cached + Validator

### ISSUE THREAD

**Issue by chrisbanes** [MobileNativeFoundation/Store#571]
I use Store's built with a custom `Validator` frequently, along with `StoreReadRequest.cached` (through the `get()`) extension to implement simple 'fetch-if-no-value' behaviour.

This was working fine in 5.0.0-beta01 and below, but 5.0.0-beta02 has broken this. The `Validator` is called, but the result doesn't seem to be used, resulting in the fetcher not being called when the validator returns `false`.

**Comment by matt-ramotar** [comment]
Hey @chrisbanes Sorry to be slow. Will prioritize this week

**Comment by digitalbuddha** [comment]
all set beta 03 is out
