### ISSUE TITLE
[BUG] Examples on https://mobilenativefoundation.github.io/Store/mutable-store/building/builder/ are wrong

### ISSUE THREAD

**Issue by Marcel348** [MobileNativeFoundation/Store#579]
1. The first example does not create MutableStore. MutableStoreBuilder should be used instead of StoreBuilder.

2. The second example Store does not write to cache and SOT after calling store.write function.
Because StoreDelegateWriteResult.Error.Exception is thrown in write function of RealStore.kt file with message "java.lang.IllegalStateException: non mutable store never call this function". 
(possible bug?)

**Comment by matt-ramotar** [comment]
Updated docs: https://store.mobilenativefoundation.org
