### ISSUE TITLE
[BUG] Documentation "Edit this page" button 404's

### ISSUE THREAD

**Issue by SebastianAigner** [MobileNativeFoundation/Store#581]
**Describe the bug**
If you click on the pencil ✏️ on any of the pages, such as https://mobilenativefoundation.github.io/Store/, you get sent to https://github.com/MobileNativeFoundation/Store/edit/master/docs/index.md, which is a 404 – page not found

<img width="742" alt="Screenshot 2023-10-07 at 16 46 09" src="https://github.com/MobileNativeFoundation/Store/assets/2178959/dd5941c3-e61d-4d1b-86bb-af15248e4ab7">

**Comment by matt-ramotar** [comment]
Thanks!
