### ISSUE TITLE
CLA

### ISSUE THREAD

**Issue by wbrawner** [MobileNativeFoundation/Store#585]
The [contributing guidelines](https://github.com/MobileNativeFoundation/Store/blob/3559a786b6ea1f6cfb117a1bc79c004a3d7a091f/CONTRIBUTING.md) mention signing the Dropbox CLA in order to make contributions. Is this still relevant given that the project is now under the Mobile Native Foundation?

**Comment by digitalbuddha** [comment]
Nope need to update that
