### ISSUE TITLE
Cache control on source of truth ?

### ISSUE THREAD

**Issue by danidiprana** [MobileNativeFoundation/Store#613]
Hello,

is there an ability or possibility in the roadmap to automatically delete/purge a setting when the size is larger than something or if the value is inactive after a while? or maybe delete old data like the LRU algorithm?

thanks

**Comment by matt-ramotar** [comment]
Answered in [Slack](https://kotlinlang.slack.com/archives/C06007Z01HU/p1710249187197409)
![Screenshot by Dropbox Capture](https://github.com/MobileNativeFoundation/Store/assets/59468153/eaa91004-21ad-4fa5-a2b8-8769723cc2f0)
