### ISSUE TITLE
Release 5.1.0-alpha03

### ISSUE THREAD

**Issue by lukisk** [MobileNativeFoundation/Store#640]

**Comment by lukisk** [comment]
@matt-ramotar  please create next alpha release.

**Comment by matt-ramotar** [comment]
Will release after #641

**Comment by lukisk** [comment]
@matt-ramotar When is the release planned for, please ?

**Comment by msfjarvis** [comment]
@matt-ramotar in case you have not figured out the Sonatype problem yet, they did an account migration that seems to have broken username authentication for a big chunk of users.

If you generate a new token following [this guide](https://central.sonatype.org/publish/generate-token/), then you can use the username and password from there as your new credentials and things should start working fine again.

**Comment by matt-ramotar** [comment]
Thanks! Just swapped, should be able to release today

**Comment by msfjarvis** [comment]
The release seems to have run into https://github.com/Kotlin/dokka/issues/2956, according to the comments reducing JVM target to 11 works around this. I can send in a PR if required.

**Comment by matt-ramotar** [comment]
@msfjarvis That would be awesome, but no pressure

**Comment by msfjarvis** [comment]
> @msfjarvis That would be awesome, but no pressure

No sweat at all, it's here: #648 

I haven't incremented the version there since I didn't know if you wanted that.

**Comment by msfjarvis** [comment]
5.1.0-alpha03 has successfully deployed: https://central.sonatype.com/search?q=g%3Aorg.mobilenativefoundation.store+version%3A5.1.0-alpha03

**Comment by matt-ramotar** [comment]
Awesome, thanks again
