### ISSUE TITLE
[BUG] Fetcher Exceptions Not Being Caught

### ISSUE THREAD

**Issue by matt-ramotar** [MobileNativeFoundation/Store#668]
Source: https://kotlinlang.slack.com/archives/C06007Z01HU/p1713182804285859

**Comment by blakelee** [comment]
Figured out that this was due to an exception when calling `store.fresh(Key)` since fresh filters out `Loading` and `NoNewData`, grabs the first element, then calls `requireData` Since the data was an error it threw an exception
